In [35]:
import numpy as np
import pandas as pd
import seaborn as sb
sb.set()
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import datasets

In [36]:
##
AND=pd.DataFrame({'x1':(0,0,1,1),'x2':(0,1,0,1),'y':(0,0,0,1)})

In [37]:
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [38]:
##First we will initailize weights, it can be positive or negative
w=np.random.randn(3)*1e-4
w

array([-3.46565085e-05, -3.42632001e-05,  4.35872845e-05])

In [39]:
## creating a simple activation function for calculating g(h)
g= lambda inputs,weights: np.where(np.dot(inputs,weights)>0,1,0)

In [40]:
def training(inputs,targets,weights,eta,n_iterations):
    #add the inputs that match the bias
    inputs=np.c_[inputs,-np.ones((len(inputs),1))]
    
    for i in range(n_iterations):
        activations=g(inputs,weights)
        weights -=eta*np.dot(np.transpose(inputs),activations-targets)
    return(weights)

In [41]:
inputs=AND[['x1','x2']]
targets=AND['y']


In [42]:
w=training(inputs,targets,w,0.25,10)
w

array([0.24996534, 0.24996574, 0.25004359])

In [44]:
#check the performance
#as you can see it gives the correct output as the actual one
g(np.c_[inputs,-np.ones((len(inputs),1))],w)

array([0, 0, 0, 1])