In [9]:
import tensorflow as tf

In [10]:
tf.__version__

'1.14.0'

In [11]:
#creating a constant variable, where we cannot change the value
a=tf.constant('Hello world')  

#session allows to allocate resourses
#in tensorflow 1 there was a provision to exexute this session"
with tf.Session() as sess:
    
    # we have to run the a in the session
    
    output=sess.run(a)
    print(output)

b'Hello world'


In [15]:
##placeholder

x=tf.placeholder(tf.string)
y=tf.placeholder(tf.float32)
z=tf.placeholder(tf.int32)

with tf.Session() as sess:
    output_x=sess.run(x,feed_dict={x:'Bangalore'})
    output_y=sess.run(y,feed_dict={x:'Test string',y:123,z:45})
    output_z=sess.run(x,feed_dict={x:'Chennai',y:78})
    print(output_x)
    print(output_y)
    print(output_z)

Bangalore
123.0
Chennai


In [16]:
##Tensorflow math
##addition
x=tf.add(5,4)
with tf.Session() as sess:
    print(sess.run(x))

9


In [18]:
## subtraction and mutiplication
y=tf.subtract(22,6)
z=tf.multiply(6,7)
with tf.Session() as sess:
    print(sess.run(y))
    print(sess.run(z))

16
42


In [21]:
#Example
x=tf.constant(20)
y=tf.constant(5)
z=tf.subtract(tf.divide(x,y),1)
with tf.Session() as sess:
    print(sess.run(z))


3.0


## Tensorflow linear functions

- variables means we can change dyring the runtime, unlike in placeholders and constant
- example weights in a neural network we need to change , variable can be used

In [23]:
x=tf.Variable(3)

In [25]:
#to run we need to initialize global variables
#in tensorflow 2.x we domt have this initializer

init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)

In [36]:
## Here the truncated_normal function tries to create random values from a  normal distribution
#Here it gives random values of shape 120X5

In [32]:
n_features=120
n_labels=5
weights=tf.Variable(tf.truncated_normal((n_features,n_labels)))
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(weights))

[[-0.03280108  0.93128866 -1.0955707   0.00528474  0.1032751 ]
 [ 0.20335768  1.8620477   0.60354304  0.22980161 -0.12271761]
 [ 0.92973423  1.6064893  -0.9637891  -0.55069923  0.35283238]
 [ 0.26762328 -0.3957463   1.5776665  -0.0965739  -0.9074353 ]
 [-1.2676735   0.17185478  0.7141409   0.35563064  1.2671201 ]
 [-0.9890567   0.1410396   1.2332644   0.19608672 -0.9009068 ]
 [ 1.2097765   0.94382066  0.13171664 -0.2883257  -1.2557821 ]
 [-0.60269696  0.22506972  0.31886065  0.5082559  -0.31618556]
 [ 0.84832376 -0.25978342  0.3719741   0.63261694 -0.30727077]
 [-0.34774086  0.12768422  1.2530209  -0.69410473  0.949584  ]
 [ 0.26976663 -0.3246252  -1.5376495   1.2184875   0.04851024]
 [ 1.8266389   0.76619273 -0.90498906 -0.06729276  0.84264547]
 [ 0.65441924 -0.6700948   0.14413378 -0.8198434   1.7159365 ]
 [-0.49807924 -0.62096     0.3410227   0.4141406  -1.1959038 ]
 [-1.3480603   0.32087645 -0.31035188 -0.28852648  0.35835037]
 [-0.4168756  -0.8074293   0.4944489   0.19676077  0.90

In [35]:
n_features=5
biases=tf.Variable(tf.zeros(n_features))
init=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(biases))

[0. 0. 0. 0. 0.]


## Tensorflow softmax

In [38]:
x=tf.nn.softmax([2.0,1.0,0.2])

In [59]:
## Example
##gives a probability value

def run():
    logits_data=[23,45,60,23,43]
    logits=tf.placeholder(tf.float32)
    
    #calculate the softmax for the logits
    softmax=tf.nn.softmax(logits)
    
    with tf.Session() as sess:
        sess.run(init)
        output=sess.run(softmax,feed_dict={logits:logits_data})
        return output
    
print(run())

[8.5330443e-17 3.0590220e-07 9.9999964e-01 8.5330443e-17 4.1399364e-08]


## One hot encoder

In [52]:
##Reduce sum
x=tf.reduce_sum([3,4,5,6,7,8])
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(x))

33


In [56]:
##Natural log
l=tf.log(100.0)
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(l))

4.6051702


In [65]:
softmax_data=[0.7,0.2,0.1]
one_hot_data=[1.0,0.0,1.0]

softmax=tf.placeholder(tf.float32)
one_hot=tf.placeholder(tf.float32)


#print cross-entropy from session
cross_entropy=-tf.reduce_sum(tf.multiply(one_hot,tf.log(softmax)))

with tf.Session() as sess:
    sess.run(init)
    output=sess.run(cross_entropy,feed_dict={one_hot:one_hot_data,softmax:softmax_data})
    print(output)

2.65926
