In [2]:
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

In [4]:
tf.keras.__version__

'2.4.0'

In [7]:
##CPU/GPU check
variable=tf.Variable([3,3])
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('CPU')

CPU


## Tensor Constant

In [8]:
a=tf.constant(4)

#when you call the variable you can see that it a tensor output unlike tensorflow 1.x
a

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [9]:
a.numpy()

4

In [15]:
b=tf.constant(1,dtype=tf.float32)
print(b)
b.numpy()

tf.Tensor(1.0, shape=(), dtype=float32)


1.0

In [18]:
c=tf.constant([[1,2],[6,7]])
print(c)
c.numpy()

tf.Tensor(
[[1 2]
 [6 7]], shape=(2, 2), dtype=int32)


array([[1, 2],
       [6, 7]])

In [22]:
#method used to generate the ones and zeros
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [21]:
print(tf.zeros(shape=(4,4)))

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)


In [28]:
x=tf.constant([[[1,2,3],[4,7,8],[9,10,12]]])
y=tf.constant([[[4,5,8],[12,13,14],[12,15,16]]])
z=tf.add(x,y)
print(z)
z.numpy()

tf.Tensor(
[[[ 5  7 11]
  [16 20 22]
  [21 25 28]]], shape=(1, 3, 3), dtype=int32)


array([[[ 5,  7, 11],
        [16, 20, 22],
        [21, 25, 28]]])

In [40]:
#random constant
tf.random.normal(shape=(3,3),mean=0,stddev=1.0)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.40901047, -1.5758065 ,  0.13174084],
       [-0.00357234, -0.5656064 ,  1.6832789 ],
       [-0.79455507,  0.98074275, -1.5388453 ]], dtype=float32)>

In [36]:
tf.random.uniform(shape=(2,2),minval=0,maxval=5,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 2],
       [2, 2]])>

## Variables

In [47]:
## variables can also be changes
#below shows the reassign code

In [53]:
x=tf.Variable(3)
x.assign(4)
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4>

In [59]:
initial=tf.random.normal(shape=(3,4))
z=tf.Variable(initial)

z

z.numpy()

array([[-0.17096156, -0.54542077,  0.17938891, -1.2170911 ],
       [ 0.6596886 ,  0.3083748 , -0.02745225,  0.03587931],
       [-1.4119891 , -0.982397  ,  0.3425752 , -0.16697963]],
      dtype=float32)

## Mathematical operations
- In tensorflow there is no concept of session
- It is same as numpy

In [16]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))
z=tf.add(a,b)
#or
y=a+b

print('z value is:',z.numpy())
print('y value is:',y.numpy())

c=a-b

print('The value of c is:',c.numpy())

d=tf.square(c)
print('The value of d is:',d.numpy())

e=tf.exp(c)
print('The value of e is:',e.numpy())

z value is: [[ 0.3401181   0.05499418]
 [ 1.4596593  -0.2799596 ]]
y value is: [[ 0.3401181   0.05499418]
 [ 1.4596593  -0.2799596 ]]
The value of c is: [[ 0.3496164   0.38759947]
 [-0.86265445 -0.4250805 ]]
The value of d is: [[0.12223163 0.15023334]
 [0.7441727  0.18069343]]
The value of e is: [[1.4185233  1.4734395 ]
 [0.4220403  0.65371716]]


## Element to element multiplication

In [19]:
a*a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.11893342, 0.04897228],
       [0.08910369, 0.12427039]], dtype=float32)>

## Broadcasting operation

In [22]:
x=tf.constant([[3,4,5],[7,8,9]])

In [23]:
x*4

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[12, 16, 20],
       [28, 32, 36]])>

 ## Transpose Matrix Multiplication

In [27]:
mat_a=tf.constant([[4,5,7]])
mat_b=tf.constant([[3,12,8]])

mat_trans=tf.transpose(a=mat_b)

In [28]:
tf.matmul(mat_a,mat_trans)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[128]])>

## Type casting the tensor

In [31]:
tensor=tf.constant([[4,3,4,5,6]])

In [33]:
tensor #it is integer data type

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[4, 3, 4, 5, 6]])>

In [37]:
tensor1=tf.cast(tensor,dtype=tf.float32)

In [38]:
tensor1 #now we can see it is converted to float32

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=array([[4., 3., 4., 5., 6.]], dtype=float32)>

## Ragged Tensor
- Ragged tensor is a tensor having one or more ragged dimensions
- ragged dimensions are dimensions that have slices having various lenghts
- there are variety of methods to declare a ragge tensor the easy possible way is using ragged constant

In [54]:
ragged=tf.ragged.constant([[4,5,6,7],[], [7,8,9],[6],[5,6,7,8,9]]) #These are called as ragged tensors
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[4, 5, 6, 7], [], [7, 8, 9], [6], [5, 6, 7, 8, 9]]>
tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)
tf.Tensor([6], shape=(1,), dtype=int32)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int32)


In [55]:
## Squared difference of tensor

In [57]:
x=[3,4,5,6]
y=5
z=tf.math.squared_difference(x,y)
z

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 1, 0, 1])>

## calculate the mean

In [59]:
x=tf.constant([[3,5],[8,9]])

In [60]:
tf.reduce_mean(input_tensor=x) #calculating mean across all axis

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [61]:
#calculating mean axis wise

In [64]:
tf.reduce_mean(input_tensor=x,axis=0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 7])>

In [65]:
tf.reduce_mean(input_tensor=x,axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 8])>

 # uniform distribution

In [69]:
tf.random.uniform(shape=(5,5),dtype=tf.float32,maxval=10)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[4.636365 , 7.031636 , 8.817318 , 3.4105277, 0.873487 ],
       [6.7518797, 9.066386 , 5.955732 , 4.9058237, 3.709638 ],
       [6.7411375, 4.3525734, 2.9690099, 1.3453841, 5.6277466],
       [2.237935 , 8.259037 , 3.1094205, 1.4969015, 8.105284 ],
       [1.5213406, 1.2733102, 8.512087 , 9.165024 , 9.656911 ]],
      dtype=float32)>

# setting the seed 
- it gives random values but does not change every time you execute
- behaves as the same way the one present in numpy package

In [74]:
tf.random.set_seed(10)
tf.random.uniform(shape=(5,5),dtype=tf.float32,maxval=10)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[6.4415097 , 8.082472  , 8.976547  , 6.3689017 , 6.270969  ],
       [9.936013  , 0.23594856, 0.36683917, 5.8605776 , 5.7403145 ],
       [0.9047401 , 5.7555532 , 2.5272822 , 1.1045039 , 6.122528  ],
       [1.2906849 , 8.966015  , 0.64798117, 8.622046  , 8.224209  ],
       [4.016037  , 7.659943  , 4.539342  , 3.2376182 , 4.617684  ]],
      dtype=float32)>

## Argmax and Arg min
- Argmax tries to give the maximum values index number (same way it behaves in numpy)
-  Argmin tries to give the min values index number (same way it behaves in numpy)

In [77]:
tensor=tf.constant([5,6,-3,5,-10,6,7,8])
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [78]:
tensor=tf.constant([5,6,-3,5,-10,6,7,8])
tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=4>